[[redirects]]
  from = "https://atwo.netlify.app/"
  to = "https://www.atwomori.net/"
  status = 301
  force = true

[[redirects]]
  from = "https://atwo.netlify.app/*"
  to = "https://www.atwomori.net/:splat"
  status = 301
  force = true

[[redirects]]
from = "/*"
to = "/404/"
status = 404

[[redirects]]
  from = "https://www.atwomori.net/cook/20220523/"
  to = "https://www.atwomori.net/cook/diary/20220523-0527/"
  status = 301

[[redirects]]
  from = "https://www.atwomori.net/cook/20220524/"
  to = "https://www.atwomori.net/cook/diary/20220523-0527/"
  status = 301

[[redirects]]
from = "/cook/20220427"
to = "/cook/diary/20220427"

[[redirects]]
from = "/cook/20220428"
to = "/cook/diary/20220428"

[[redirects]]
from = "/cook/20220503"
to = "/cook/diary/20220503-0506"

[[redirects]]
from = "/cook/20220504"
to = "/cook/diary/20220503-0506"

[[redirects]]
from = "/cook/20220505"
to = "/cook/diary/20220503-0506"

[[redirects]]
from = "/cook/20220506"
to = "/cook/diary/20220503-0506"

[[redirects]]
from = "/cook/20220509"
to = "/cook/diary/20220509-0513"

[[redirects]]
from = "/cook/20220510"
to = "/cook/diary/20220509-0513"

[[redirects]]
from = "/cook/20220511"
to = "/cook/diary/20220509-0513"

[[redirects]]
from = "/cook/20220512"
to = "/cook/diary/20220509-0513"

[[redirects]]
from = "/cook/20220513"
to = "/cook/diary/20220509-0513"

[[redirects]]
from = "/cook/20220516"
to = "/cook/diary/20220516-0520"

[[redirects]]
from = "/cook/20220517"
to = "/cook/diary/20220516-0520"

[[redirects]]
from = "/cook/20220518"
to = "/cook/diary/20220516-0520"

[[redirects]]
from = "/cook/20220519"
to = "/cook/diary/20220516-0520"
